'PR: waiting for review':
  - '*'  
  - '.github/**/*' 
  - 'src/**/*'
  - 'test/**/*'
  - '.editorconfig'
  - '.eslintignore'
  - '.eslintrc.js'
  - '.gitignore'

'PR: dependencies':  
  - 'package-lock.json'
  - 'package.json'
